CREATE TABLE [dbo].[MyTable]
(
  [Id] INT NOT NULL PRIMARY KEY,
  [Name] NVARCHAR(100) NOT NULL,
  [CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
  [Email] NVARCHAR(255) NULL,
  [IsActive] BIT NOT NULL DEFAULT 1
)
